<?php
namespace App\Controllers\Customer;
use App\Core\Controller;
use App\Helpers\CustomerAuth;

class Addresses extends Controller
{
    public function index(): void { $this->handleCors(); if(!$this->isGet())$this->error('Method not allowed',405); $u=$this->customer(); $rows=$this->db()->query('SELECT * FROM vp_customer_addresses WHERE customer_id=? ORDER BY is_default DESC,updated_at DESC,id DESC',[(int)$u['id']])->result_array(); $this->success(['items'=>array_map([$this,'present'],$rows?:[])],'Addresses loaded'); }
    public function show($id=null): void { $this->handleCors(); if(!$this->isGet())$this->error('Method not allowed',405); $u=$this->customer(); $row=$this->find((int)$id,(int)$u['id']); if(!$row)$this->error('Address not found',404); $this->success($this->present($row),'Address loaded'); }
    public function save($id=null): void {
        $this->handleCors(); if(!$this->isPost())$this->error('Method not allowed',405); $u=$this->customer(); $id=(int)$id; $body=$this->getBody();
        foreach(['label','recipient_name','recipient_phone','address_line'] as $field) if(trim((string)($body[$field]??''))==='')$this->error("{$field} is required",422);
        $lat=$this->coordinate($body,'latitude'); $lng=$this->coordinate($body,'longitude'); if(($lat===null)!==($lng===null))$this->error('Latitude and longitude must be supplied together',422);
        $now=$GLOBALS['now']??date('Y-m-d H:i:s'); $payload=['label'=>trim((string)$body['label']),'recipient_name'=>trim((string)$body['recipient_name']),'recipient_phone'=>trim((string)$body['recipient_phone']),'address_line'=>trim((string)$body['address_line']),'notes'=>trim((string)($body['notes']??''))?:null,'area_id'=>trim((string)($body['area_id']??''))?:null,'area_name'=>trim((string)($body['area_name']??''))?:null,'postal_code'=>trim((string)($body['postal_code']??''))?:null,'latitude'=>$lat,'longitude'=>$lng,'updated_at'=>$now];
        if($id>0&&!$this->find($id,(int)$u['id']))$this->error('Address not found',404); $this->db()->beginTransaction(); try { $count=(int)($this->db()->query('SELECT COUNT(*) total FROM vp_customer_addresses WHERE customer_id=?',[(int)$u['id']])->row_array()['total']??0); $requestedDefault=filter_var($body['is_default']??false,FILTER_VALIDATE_BOOLEAN); $makeDefault=$requestedDefault||$count===0; if($makeDefault)$this->db()->query('UPDATE vp_customer_addresses SET is_default=0,updated_at=? WHERE customer_id=?',[$now,(int)$u['id']]); if($id>0){$payload['is_default']=$makeDefault?1:(int)($this->find($id,(int)$u['id'])['is_default']??0);$this->db()->update('vp_customer_addresses',$payload,['id'=>$id,'customer_id'=>(int)$u['id']]);}else{$payload+=['customer_id'=>(int)$u['id'],'is_default'=>$makeDefault?1:0,'created_at'=>$now];$id=(int)$this->db()->insert('vp_customer_addresses',$payload);} $this->db()->commit(); $this->success($this->present($this->find($id,(int)$u['id'])),'Address saved'); }catch(\Throwable $e){$this->db()->rollback();$this->error('Failed to save address',500);}
    }
    public function set_default($id=null): void { $this->handleCors(); if(!$this->isPost())$this->error('Method not allowed',405);$u=$this->customer();$id=(int)$id;if(!$this->find($id,(int)$u['id']))$this->error('Address not found',404);$now=$GLOBALS['now']??date('Y-m-d H:i:s');$this->db()->beginTransaction();try{$this->db()->query('UPDATE vp_customer_addresses SET is_default=0,updated_at=? WHERE customer_id=?',[$now,(int)$u['id']]);$this->db()->update('vp_customer_addresses',['is_default'=>1,'updated_at'=>$now],['id'=>$id,'customer_id'=>(int)$u['id']]);$this->db()->commit();$this->success($this->present($this->find($id,(int)$u['id'])),'Default address updated');}catch(\Throwable $e){$this->db()->rollback();$this->error('Failed to set default address',500);}}
    public function remove($id=null): void { $this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$u=$this->customer();$id=(int)$id;$row=$this->find($id,(int)$u['id']);if(!$row)$this->error('Address not found',404);$this->db()->delete('vp_customer_addresses',['id'=>$id,'customer_id'=>(int)$u['id']]);if((int)$row['is_default']===1){$next=$this->db()->query('SELECT id FROM vp_customer_addresses WHERE customer_id=? ORDER BY updated_at DESC,id DESC LIMIT 1',[(int)$u['id']])->row_array();if($next)$this->db()->update('vp_customer_addresses',['is_default'=>1],['id'=>(int)$next['id']]);}$this->success(null,'Address deleted');}
    private function customer(): array {$u=CustomerAuth::user();if(!$u)$this->error('Unauthorized',401);return $u;}
    private function find(int $id,int $customerId): ?array {$row=$this->db()->query('SELECT * FROM vp_customer_addresses WHERE id=? AND customer_id=? LIMIT 1',[$id,$customerId])->row_array();return $row?:null;}
    private function coordinate(array $body,string $name): ?float {if(!array_key_exists($name,$body)||$body[$name]==='')return null;if(!is_numeric($body[$name]))$this->error("{$name} must be numeric",422);return (float)$body[$name];}
    private function present(array $r): array {return ['id'=>(int)$r['id'],'label'=>$r['label'],'recipientName'=>$r['recipient_name'],'recipientPhone'=>$r['recipient_phone'],'addressLine'=>$r['address_line'],'notes'=>$r['notes'],'areaId'=>$r['area_id'],'areaName'=>$r['area_name'],'postalCode'=>$r['postal_code'],'latitude'=>$r['latitude']===null?null:(float)$r['latitude'],'longitude'=>$r['longitude']===null?null:(float)$r['longitude'],'isDefault'=>(bool)$r['is_default']];}
}
