<?php
namespace App\Controllers\Customer;
use App\Core\Controller;
use App\Helpers\CustomerAuth;

class Addresses extends Controller
{
    public function index(): void { $this->handleCors(); if(!$this->isGet())$this->error('Method not allowed',405); $u=$this->customer(); $rows=$this->db()->query('SELECT * FROM vp_customer_addresses WHERE customer_id=? ORDER BY is_default DESC,updated_at DESC,id DESC',[(int)$u['id']])->result_array(); $this->success(['items'=>array_map([$this,'present'],$rows?:[])],'Addresses loaded'); }
    public function show($id=null): void { $this->handleCors(); if(!$this->isGet())$this->error('Method not allowed',405); $u=$this->customer(); $row=$this->find((int)$id,(int)$u['id']); if(!$row)$this->error('Address not found',404); $this->success($this->present($row),'Address loaded'); }
    public function save($id=null): void {
        $this->handleCors(); if(!$this->isPost())$this->error('Method not allowed',405); $u=$this->customer(); $id=(int)$id; $body=$this->getBody();
        foreach(['label','recipient_name','recipient_phone','address_line'] as $field) if(trim((string)($body[$field]??''))==='')$this->error("{$field} is required",422);
        $lat=$this->coordinate($body,'latitude'); $lng=$this->coordinate($body,'longitude'); if(($lat===null)!==($lng===null))$this->error('Latitude and longitude must be supplied together',422);
        $now=$GLOBALS['now']??date('Y-m-d H:i:s'); $payload=['label'=>trim((string)$body['label']),'recipient_name'=>trim((string)$body['recipient_name']),'recipient_phone'=>trim((string)$body['recipient_phone']),'address_line'=>trim((string)$body['address_line']),'notes'=>trim((string)($body['notes']??''))?:null,'area_id'=>trim((string)($body['area_id']??''))?:null,'area_name'=>trim((string)($body['area_name']??''))?:null,'province_id'=>trim((string)($body['province_id']??''))?:null,'province_name'=>trim((string)($body['province_name']??''))?:null,'regency_id'=>trim((string)($body['regency_id']??''))?:null,'regency_name'=>trim((string)($body['regency_name']??''))?:null,'district_id'=>trim((string)($body['district_id']??''))?:null,'district_name'=>trim((string)($body['district_name']??''))?:null,'village_id'=>trim((string)($body['village_id']??''))?:null,'village_name'=>trim((string)($body['village_name']??''))?:null,'postal_code'=>trim((string)($body['postal_code']??''))?:null,'latitude'=>$lat,'longitude'=>$lng,'updated_at'=>$now];
        if($id>0&&!$this->find($id,(int)$u['id']))$this->error('Address not found',404); $this->db()->beginTransaction(); try { $count=(int)($this->db()->query('SELECT COUNT(*) total FROM vp_customer_addresses WHERE customer_id=?',[(int)$u['id']])->row_array()['total']??0); $requestedDefault=filter_var($body['is_default']??false,FILTER_VALIDATE_BOOLEAN); $makeDefault=$requestedDefault||$count===0; if($makeDefault)$this->db()->query('UPDATE vp_customer_addresses SET is_default=0,updated_at=? WHERE customer_id=?',[$now,(int)$u['id']]); if($id>0){$payload['is_default']=$makeDefault?1:(int)($this->find($id,(int)$u['id'])['is_default']??0);$this->db()->update('vp_customer_addresses',$payload,['id'=>$id,'customer_id'=>(int)$u['id']]);}else{$payload+=['customer_id'=>(int)$u['id'],'is_default'=>$makeDefault?1:0,'created_at'=>$now];$id=(int)$this->db()->insert('vp_customer_addresses',$payload);} $this->db()->commit(); $this->success($this->present($this->find($id,(int)$u['id'])),'Address saved'); }catch(\Throwable $e){$this->db()->rollback();$this->error('Failed to save address',500);}
    }
    public function set_default($id=null): void { $this->handleCors(); if(!$this->isPost())$this->error('Method not allowed',405);$u=$this->customer();$id=(int)$id;if(!$this->find($id,(int)$u['id']))$this->error('Address not found',404);$now=$GLOBALS['now']??date('Y-m-d H:i:s');$this->db()->beginTransaction();try{$this->db()->query('UPDATE vp_customer_addresses SET is_default=0,updated_at=? WHERE customer_id=?',[$now,(int)$u['id']]);$this->db()->update('vp_customer_addresses',['is_default'=>1,'updated_at'=>$now],['id'=>$id,'customer_id'=>(int)$u['id']]);$this->db()->commit();$this->success($this->present($this->find($id,(int)$u['id'])),'Default address updated');}catch(\Throwable $e){$this->db()->rollback();$this->error('Failed to set default address',500);}}
    public function lookup(): void {
        $this->handleCors(); if(!$this->isPost())$this->error('Method not allowed',405); $this->customer();
        $b=$this->getBody();
        $village=trim((string)($b['village_name']??'')); $district=trim((string)($b['district_name']??'')); $regency=trim((string)($b['regency_name']??'')); $province=trim((string)($b['province_name']??''));
        $input=implode(', ', array_values(array_filter([$village,$district,$regency,$province])));
        if($input==='')$this->error('Pilih wilayah (kelurahan/kecamatan/kota) terlebih dahulu',422);
        $key=(string)(\Env::BITESHIP_API_KEY??''); if($key==='')$this->error('Biteship is not configured',503);
        $c=curl_init('https://api.biteship.com/v1/maps/areas?countries=ID&input='.rawurlencode($input));
        curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20,CURLOPT_HTTPHEADER=>['Authorization: '.$key]]);
        $raw=curl_exec($c); $status=(int)curl_getinfo($c,CURLINFO_HTTP_CODE); curl_close($c);
        $data=json_decode((string)$raw,true);
        if($status<200||$status>=300||!is_array($data))$this->error('Biteship area lookup failed',502);
        $areas=$data['areas']??[]; if(!$areas)$this->error('Wilayah tidak ditemukan di Biteship',404);
        $norm=fn($s)=>strtolower(preg_replace('/[^a-z0-9]+/i','',(string)$s));
        $best=null;
        foreach($areas as $a){ $hay=$norm(($a['name']??'').' '.($a['administrative_division_level_3_name']??'').' '.($a['administrative_division_level_4_name']??'')); $score=($village!==''&&str_contains($hay,$norm($village))?4:0)+($district!==''&&str_contains($hay,$norm($district))?2:0)+($regency!==''&&str_contains($hay,$norm($regency))?1:0); if($best===null||$score>$best['score'])$best=['score'=>$score,'a'=>$a]; }
        $a=$best['a'];
        $this->success(['areaId'=>(string)($a['id']??''),'areaName'=>(string)($a['name']??''),'postalCode'=>(string)($a['postal_code']??''),'provinceName'=>(string)($a['administrative_division_level_1_name']??''),'regencyName'=>(string)($a['administrative_division_level_2_name']??''),'districtName'=>(string)($a['administrative_division_level_3_name']??''),'villageName'=>(string)($a['administrative_division_level_4_name']??'')],'Area resolved');
    }
    public function remove($id=null): void { $this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$u=$this->customer();$id=(int)$id;$row=$this->find($id,(int)$u['id']);if(!$row)$this->error('Address not found',404);$this->db()->delete('vp_customer_addresses',['id'=>$id,'customer_id'=>(int)$u['id']]);if((int)$row['is_default']===1){$next=$this->db()->query('SELECT id FROM vp_customer_addresses WHERE customer_id=? ORDER BY updated_at DESC,id DESC LIMIT 1',[(int)$u['id']])->row_array();if($next)$this->db()->update('vp_customer_addresses',['is_default'=>1],['id'=>(int)$next['id']]);}$this->success(null,'Address deleted');}
    private function customer(): array {$u=CustomerAuth::user();if(!$u)$this->error('Unauthorized',401);return $u;}
    private function find(int $id,int $customerId): ?array {$row=$this->db()->query('SELECT * FROM vp_customer_addresses WHERE id=? AND customer_id=? LIMIT 1',[$id,$customerId])->row_array();return $row?:null;}
    private function coordinate(array $body,string $name): ?float {if(!array_key_exists($name,$body)||$body[$name]==='')return null;if(!is_numeric($body[$name]))$this->error("{$name} must be numeric",422);return (float)$body[$name];}
    private function present(array $r): array {return ['id'=>(int)$r['id'],'label'=>$r['label'],'recipientName'=>$r['recipient_name'],'recipientPhone'=>$r['recipient_phone'],'addressLine'=>$r['address_line'],'notes'=>$r['notes'],'areaId'=>$r['area_id'],'areaName'=>$r['area_name'],'provinceId'=>$r['province_id']??null,'provinceName'=>$r['province_name']??null,'regencyId'=>$r['regency_id']??null,'regencyName'=>$r['regency_name']??null,'districtId'=>$r['district_id']??null,'districtName'=>$r['district_name']??null,'villageId'=>$r['village_id']??null,'villageName'=>$r['village_name']??null,'postalCode'=>$r['postal_code'],'latitude'=>$r['latitude']===null?null:(float)$r['latitude'],'longitude'=>$r['longitude']===null?null:(float)$r['longitude'],'isDefault'=>(bool)$r['is_default']];}
}
