<?php
namespace App\Controllers\Customer;
use App\Core\Controller;use App\Helpers\CustomerAuth;
class Cart extends Controller {
 public function index():void{$this->handleCors();if(!$this->isGet())$this->error('Method not allowed',405);$u=$this->customer();$rows=$this->db()->query('SELECT ci.*,p.name,p.slug,p.cover_image_url,c.selections_json,c.note FROM vp_cart_items ci INNER JOIN vp_product_configurations c ON c.id=ci.configuration_id INNER JOIN vp_products p ON p.id=c.product_id WHERE ci.customer_id=? ORDER BY ci.updated_at DESC',[(int)$u['id']])->result_array()?:[];$items=array_map(function($r){return ['id'=>(int)$r['id'],'configurationId'=>(int)$r['configuration_id'],'name'=>$r['name'],'slug'=>$r['slug'],'image'=>$r['cover_image_url'],'quantity'=>(int)$r['quantity'],'unitPrice'=>(float)$r['unit_price'],'totalPrice'=>(float)$r['unit_price']*(int)$r['quantity'],'selections'=>json_decode($r['selections_json'],true)?:[],'note'=>$r['note']];},$rows);$this->success(['items'=>$items,'total'=>array_sum(array_column($items,'totalPrice'))],'Cart loaded');}
 public function add():void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$u=$this->customer();$b=$this->getBody();$productId=(int)($b['product_id']??0);$qty=max(1,min(100,(int)($b['quantity']??1)));$p=$this->db()->query("SELECT id,base_price FROM vp_products WHERE id=? AND status='published' LIMIT 1",[$productId])->row_array();if(!$p)$this->error('Product not found',404);$selected=array_values(array_unique(array_map('intval',$b['option_value_ids']??[])));$groups=$this->db()->query('SELECT id,name,is_required FROM vp_product_option_groups WHERE product_id=?',[$productId])->result_array()?:[];$selections=[];$price=(float)$p['base_price'];foreach($groups as $g){$values=$this->db()->query('SELECT id,name,price_delta FROM vp_product_option_values WHERE option_group_id=? AND is_active=1',[(int)$g['id']])->result_array()?:[];$chosen=array_values(array_filter($values,fn($v)=>in_array((int)$v['id'],$selected,true)));if((int)$g['is_required']===1&&count($chosen)!==1)$this->error('Choose one option for '.$g['name'],422);foreach($chosen as $v){$price+=(float)$v['price_delta'];$selections[]=['groupId'=>(int)$g['id'],'group'=>$g['name'],'valueId'=>(int)$v['id'],'value'=>$v['name'],'priceDelta'=>(float)$v['price_delta']];}}$now=$GLOBALS['now']??date('Y-m-d H:i:s');$this->db()->beginTransaction();try{$configId=(int)$this->db()->insert('vp_product_configurations',['customer_id'=>(int)$u['id'],'product_id'=>$productId,'selections_json'=>json_encode($selections),'quantity'=>$qty,'unit_price'=>$price,'note'=>trim((string)($b['note']??''))?:null,'status'=>'in_cart','created_at'=>$now,'updated_at'=>$now]);foreach(array_unique(array_map('intval',$b['upload_ids']??[])) as $uploadId){$ok=$this->db()->update('vp_design_uploads',['configuration_id'=>$configId],['id'=>$uploadId,'customer_id'=>(int)$u['id'],'product_id'=>$productId]);if(!$ok)throw new \RuntimeException('Invalid upload');}$cartId=$this->db()->insert('vp_cart_items',['customer_id'=>(int)$u['id'],'configuration_id'=>$configId,'quantity'=>$qty,'unit_price'=>$price,'created_at'=>$now,'updated_at'=>$now]);$this->db()->commit();$this->success(['id'=>(int)$cartId,'configurationId'=>$configId],'Added to cart');}catch(\Throwable $e){$this->db()->rollback();$this->error('Failed to add cart item',500);}}
 public function update($id=null):void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$u=$this->customer();$qty=max(1,min(100,(int)($this->getBody()['quantity']??1)));$ok=$this->db()->update('vp_cart_items',['quantity'=>$qty,'updated_at'=>$GLOBALS['now']??date('Y-m-d H:i:s')],['id'=>(int)$id,'customer_id'=>(int)$u['id']]);if(!$ok)$this->error('Cart item not found',404);$this->success(null,'Cart updated');}
 public function remove($id=null):void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$u=$this->customer();$ok=$this->db()->delete('vp_cart_items',['id'=>(int)$id,'customer_id'=>(int)$u['id']]);if(!$ok)$this->error('Cart item not found',404);$this->success(null,'Cart item removed');}
 private function customer():array{$u=CustomerAuth::user();if(!$u)$this->error('Unauthorized',401);return $u;}
}
