<?php
/** Run only with an empty/approved target database after a backup. */
function db(string $host, string $user, string $pass, string $name): mysqli { $db = new mysqli($host, $user, $pass, $name); if ($db->connect_error) throw new RuntimeException($db->connect_error); $db->set_charset('utf8mb4'); return $db; }
function slug(string $value, int $id): string { $value = strtolower(trim(preg_replace('/[^a-z0-9]+/i', '-', $value), '-')); return ($value ?: 'product') . '-' . $id; }
$source = db(getenv('OLD_DB_HOST') ?: 'localhost', getenv('OLD_DB_USER'), getenv('OLD_DB_PASS'), getenv('OLD_DB_NAME') ?: 'vita');
$target = db(getenv('NEW_DB_HOST') ?: 'localhost', getenv('NEW_DB_USER'), getenv('NEW_DB_PASS'), getenv('NEW_DB_NAME') ?: 'vitapictura');
$existing = (int)($target->query('SELECT COUNT(*) total FROM vp_products')->fetch_assoc()['total'] ?? 0);
if ($existing > 0) throw new RuntimeException('Target already has products; refusing non-idempotent import.');
$now = date('Y-m-d H:i:s'); $target->begin_transaction();
try {
  $categoryMap=[]; $groups=$source->query('SELECT DISTINCT grup FROM produk ORDER BY grup');
  $insertCategory=$target->prepare("INSERT INTO vp_categories(name,slug,description,sort_order,is_featured,status,created_at,updated_at) VALUES(?,?,?,?,?,'published',?,?)");
  while($g=$groups->fetch_assoc()){ $group=(int)$g['grup']; $name='Migrated group '.$group; $order=$group; $featured=0; $insertCategory->bind_param('ssiiiss',$name,$slug,$description,$order,$featured,$now,$now); $slug='migrated-group-'.$group; $description='Produk hasil migrasi ABFLab; kategori perlu dirapikan admin.'; $insertCategory->execute(); $categoryMap[$group]=$target->insert_id; }
  $productMap=[]; $q=$source->query('SELECT * FROM produk ORDER BY produk_id');
  $insertProduct=$target->prepare("INSERT INTO vp_products(legacy_product_id,category_id,name,slug,short_description,description,base_price,weight_grams,length_mm,width_mm,height_mm,cover_image_url,is_featured,popularity,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,'published',?,?)");
  while($p=$q->fetch_assoc()){ $legacy=(int)$p['produk_id'];$category=$categoryMap[(int)$p['grup']];$name=$p['produk'];$productSlug=slug($name,$legacy);$short=substr((string)$p['detail'],0,1000);$detail=(string)$p['detail'];$price=(float)$p['harga'];$weight=(int)$p['berat'];$length=(int)$p['p']*10;$width=(int)$p['l']*10;$height=(int)$p['t']*10;$cover=null;$featured=0;$popularity=(int)$p['freq'];$insertProduct->bind_param('iissssdiiiisiiss',$legacy,$category,$name,$productSlug,$short,$detail,$price,$weight,$length,$width,$height,$cover,$featured,$popularity,$now,$now); $insertProduct->execute();$productMap[$legacy]=$target->insert_id; }
  $optionGroupMap=[];$q=$source->query('SELECT * FROM varian_grup_1 ORDER BY vg1_id');$insertGroup=$target->prepare('INSERT INTO vp_product_option_groups(product_id,name,is_required,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?)');
  while($g=$q->fetch_assoc()){if(!isset($productMap[(int)$g['produk_id']]))continue;$pid=$productMap[(int)$g['produk_id']];$name=$g['vg'];$required=1;$order=(int)$g['vg1_id'];$insertGroup->bind_param('isiiss',$pid,$name,$required,$order,$now,$now);$insertGroup->execute();$optionGroupMap[(int)$g['vg1_id']]=$target->insert_id;}
  $insertValue=$target->prepare('INSERT INTO vp_product_option_values(option_group_id,name,price_delta,weight_delta_grams,length_delta_mm,width_delta_mm,height_delta_mm,sort_order,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$q=$source->query('SELECT * FROM varian_1 ORDER BY varian_id');
  while($v=$q->fetch_assoc()){if(!isset($optionGroupMap[(int)$v['vg1_id']]))continue;$gid=$optionGroupMap[(int)$v['vg1_id']];$name=$v['varian'];$price=(float)$v['harga'];$weight=(int)$v['berat'];$l=(int)$v['p']*10;$w=(int)$v['l']*10;$h=(int)$v['t']*10;$sort=(int)$v['varian_id'];$active=1;$insertValue->bind_param('isdiiiiiiss',$gid,$name,$price,$weight,$l,$w,$h,$sort,$active,$now,$now);$insertValue->execute();}
  $q=$source->query('SELECT g.vg1_id,g.vg,v.vg2_id,v.v2_head_id,v.varian_id,v.harga,v.berat,v.p,v.l,v.t,h.v2_head FROM varian_2 v INNER JOIN varian_grup_2 g ON g.vg2_id=v.vg2_id LEFT JOIN v2_head h ON h.v2_head_id=v.v2_head_id ORDER BY v.varian_id');
  while($v=$q->fetch_assoc()){if(!isset($optionGroupMap[(int)$v['vg1_id']]))continue;$base=$optionGroupMap[(int)$v['vg1_id']];$name=$v['vg'].' — '.($v['v2_head'] ?: ('Option '.$v['varian_id']));$required=0;$sort=(int)$v['vg2_id'];$insertGroup->bind_param('isiiss',$base,$name,$required,$sort,$now,$now);$insertGroup->execute();$gid=$target->insert_id;$valueName=$v['v2_head'] ?: ('Option '.$v['varian_id']);$price=(float)$v['harga'];$weight=(int)$v['berat'];$l=(int)$v['p']*10;$w=(int)$v['l']*10;$h=(int)$v['t']*10;$active=1;$insertValue->bind_param('isdiiiiiiss',$gid,$valueName,$price,$weight,$l,$w,$h,$sort,$active,$now,$now);$insertValue->execute();}
  $target->commit(); echo "Migrated products=".count($productMap)." categories=".count($categoryMap)."\n";
} catch(Throwable $e) { $target->rollback(); throw $e; }
