<?php
namespace App\Controllers\Admin;use App\Core\Controller;use App\Helpers\AdminAuth;
class Options extends Controller {
 public function index($productId=null):void{$this->handleCors();$this->admin();$pid=(int)$productId;$groups=$this->db()->query('SELECT id,name,group_level,parent_group_id,is_required,sort_order FROM vp_product_option_groups WHERE product_id=? ORDER BY group_level,sort_order,id',[$pid])->result_array()?:[];foreach($groups as &$g){$g['id']=(int)$g['id'];$g['group_level']=(int)$g['group_level'];$g['parent_group_id']=$g['parent_group_id']!==null?(int)$g['parent_group_id']:null;$g['is_required']=(int)$g['is_required'];$g['sort_order']=(int)$g['sort_order'];$vals=$this->db()->query('SELECT id,name,image_suffix,parent_value_id,price_delta,weight_delta_grams,length_delta_mm,width_delta_mm,height_delta_mm,sort_order,is_active FROM vp_product_option_values WHERE option_group_id=? ORDER BY sort_order,id',[(int)$g['id']])->result_array()?:[];foreach($vals as &$v){$v['id']=(int)$v['id'];$v['parent_value_id']=$v['parent_value_id']!==null?(int)$v['parent_value_id']:null;$v['price_delta']=(float)$v['price_delta'];$v['weight_delta_grams']=(int)$v['weight_delta_grams'];$v['length_delta_mm']=(int)$v['length_delta_mm'];$v['width_delta_mm']=(int)$v['width_delta_mm'];$v['height_delta_mm']=(int)$v['height_delta_mm'];$v['sort_order']=(int)$v['sort_order'];$v['is_active']=(int)$v['is_active'];}unset($v);$g['values']=$vals;}unset($g);$this->success(['items'=>$groups],'Options loaded');}
 public function save_group($id=null):void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->admin();$b=$this->getBody();$id=(int)$id;$name=trim((string)($b['name']??''));if($name==='')$this->error('Nama grup wajib diisi',422);$level=(int)($b['group_level']??1);if(!in_array($level,[1,2],true))$level=1;$parent=($level===2&&!empty($b['parent_group_id']))?(int)$b['parent_group_id']:null;if($level===2&&$parent===null)$this->error('Grup turunan harus punya grup induk',422);$required=!empty($b['is_required'])?1:0;$sort=(int)($b['sort_order']??0);$now=$GLOBALS['now']??date('Y-m-d H:i:s');if($id>0){$g=$this->db()->query('SELECT id FROM vp_product_option_groups WHERE id=? LIMIT 1',[$id])->row_array();if(!$g)$this->error('Grup tidak ditemukan',404);$this->db()->update('vp_product_option_groups',['name'=>$name,'group_level'=>$level,'parent_group_id'=>$parent,'is_required'=>$required,'sort_order'=>$sort,'updated_at'=>$now],['id'=>$id]);}else{$pid=(int)($b['product_id']??0);if(!$this->db()->query('SELECT id FROM vp_products WHERE id=? LIMIT 1',[$pid])->row_array())$this->error('Produk tidak ditemukan',404);$id=(int)$this->db()->insert('vp_product_option_groups',['product_id'=>$pid,'legacy_vg_id'=>null,'name'=>$name,'group_level'=>$level,'parent_group_id'=>$parent,'is_required'=>$required,'sort_order'=>$sort,'created_at'=>$now,'updated_at'=>$now]);} $this->success(['id'=>$id],'Grup disimpan');}
 public function remove_group($id=null):void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->admin();$id=(int)$id;$this->db()->delete('vp_product_option_groups',['id'=>$id]);$this->success(null,'Grup dihapus');}
 public function save_value($id=null):void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->admin();$b=$this->getBody();$id=(int)$id;$name=trim((string)($b['name']??''));if($name==='')$this->error('Nama nilai wajib diisi',422);$now=$GLOBALS['now']??date('Y-m-d H:i:s');$suffix=trim((string)($b['image_suffix']??''))?:null;$parent=!empty($b['parent_value_id'])?(int)$b['parent_value_id']:null;$data=['name'=>$name,'image_suffix'=>$suffix,'parent_value_id'=>$parent,'price_delta'=>(float)($b['price_delta']??0),'weight_delta_grams'=>(int)($b['weight_delta_grams']??0),'length_delta_mm'=>(int)($b['length_delta_mm']??0),'width_delta_mm'=>(int)($b['width_delta_mm']??0),'height_delta_mm'=>(int)($b['height_delta_mm']??0),'sort_order'=>(int)($b['sort_order']??0),'is_active'=>!empty($b['is_active'])?1:0,'updated_at'=>$now];if($id>0){if(!$this->db()->query('SELECT id FROM vp_product_option_values WHERE id=? LIMIT 1',[$id])->row_array())$this->error('Nilai tidak ditemukan',404);$this->db()->update('vp_product_option_values',$data,['id'=>$id]);}else{$gid=(int)($b['option_group_id']??0);if(!$this->db()->query('SELECT id FROM vp_product_option_groups WHERE id=? LIMIT 1',[$gid])->row_array())$this->error('Grup tidak ditemukan',404);$data['option_group_id']=$gid;$data['legacy_varian_id']=null;$data['created_at']=$now;$id=(int)$this->db()->insert('vp_product_option_values',$data);} $this->success(['id'=>$id],'Nilai disimpan');}
 public function remove_value($id=null):void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->admin();$id=(int)$id;$this->db()->delete('vp_product_option_values',['id'=>$id]);$this->success(null,'Nilai dihapus');}
 private function admin():array{$a=AdminAuth::user();if(!$a)$this->error('Unauthorized',401);return $a;}
}
