<?php
namespace App\Controllers\Admin;use App\Core\Controller;use App\Helpers\AdminAuth;
class Products extends Controller {
 public function index():void{$this->handleCors();$this->admin();$rows=$this->db()->query('SELECT p.id,p.name,p.slug,p.category_id,p.base_price,p.cover_image_url,p.is_featured,p.status,p.popularity,p.updated_at,c.name category_name FROM vp_products p LEFT JOIN vp_categories c ON c.id=p.category_id ORDER BY p.name LIMIT 500')->result_array()?:[];foreach($rows as &$r){$r['id']=(int)$r['id'];$r['category_id']=$r['category_id']!==null?(int)$r['category_id']:null;$r['base_price']=(float)$r['base_price'];$r['is_featured']=(int)$r['is_featured'];$r['popularity']=(int)$r['popularity'];}$this->success(['items'=>$rows],'Products loaded');}
 public function show($id=null):void{$this->handleCors();$this->admin();$r=$this->db()->query('SELECT * FROM vp_products WHERE id=? LIMIT 1',[(int)$id])->row_array();if(!$r)$this->error('Produk tidak ditemukan',404);$r['id']=(int)$r['id'];$r['category_id']=$r['category_id']!==null?(int)$r['category_id']:null;$r['base_price']=(float)$r['base_price'];$r['is_featured']=(int)$r['is_featured'];$r['popularity']=(int)$r['popularity'];unset($r['mal_json']);$this->success($r,'Product loaded');}
 public function save($id=null):void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->admin();$b=$this->getBody();$id=(int)$id;$name=trim((string)($b['name']??''));if($name==='')$this->error('Nama produk wajib diisi',422);$slug=trim((string)($b['slug']??''));if($slug==='')$slug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$name),'-'));if($slug==='')$slug='produk';$category=(isset($b['category_id'])&&$b['category_id']!==''&&$b['category_id']!==null)?(int)$b['category_id']:null;if($category!==null){if(!$this->db()->query('SELECT id FROM vp_categories WHERE id=? LIMIT 1',[$category])->row_array())$this->error('Kategori tidak ditemukan',422);}$status=(string)($b['status']??'published');if(!in_array($status,['draft','published','archived'],true))$status='published';$base=$slug;$suffix=1;while($this->db()->query('SELECT id FROM vp_products WHERE slug=? AND id<>? LIMIT 1',[$slug,$id])->row_array()){$slug=$base.'-'.(++$suffix);}$now=$GLOBALS['now']??date('Y-m-d H:i:s');$int=fn($k)=>isset($b[$k])&&$b[$k]!==''?(int)$b[$k]:null;$data=['category_id'=>$category,'name'=>$name,'slug'=>$slug,'short_description'=>trim((string)($b['short_description']??''))?:null,'description'=>trim((string)($b['description']??''))?:null,'base_price'=>(float)($b['base_price']??0),'weight_grams'=>max(0,(int)($b['weight_grams']??0)),'length_mm'=>$int('length_mm'),'width_mm'=>$int('width_mm'),'height_mm'=>$int('height_mm'),'cover_image_url'=>trim((string)($b['cover_image_url']??''))?:null,'is_featured'=>!empty($b['is_featured'])?1:0,'popularity'=>max(0,(int)($b['popularity']??0)),'status'=>$status,'updated_at'=>$now];if($id>0){if(!$this->db()->query('SELECT id FROM vp_products WHERE id=? LIMIT 1',[$id])->row_array())$this->error('Produk tidak ditemukan',404);$this->db()->update('vp_products',$data,['id'=>$id]);}else{$data['created_at']=$now;$id=(int)$this->db()->insert('vp_products',$data);}$r=$this->db()->query('SELECT id,name,slug,category_id,base_price,status,is_featured FROM vp_products WHERE id=? LIMIT 1',[$id])->row_array();$r['id']=(int)$r['id'];$r['category_id']=$r['category_id']!==null?(int)$r['category_id']:null;$r['base_price']=(float)$r['base_price'];$r['is_featured']=(int)$r['is_featured'];$this->success($r,'Produk disimpan');}
 public function remove($id=null):void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->admin();$id=(int)$id;$count=(int)($this->db()->query('SELECT COUNT(*) c FROM vp_product_configurations WHERE product_id=?',[$id])->row_array()['c']??0);if($count>0)$this->error('Produk tidak bisa dihapus karena dipakai pada '.$count.' konfigurasi/pesanan.',422);$this->db()->delete('vp_products',['id'=>$id]);$this->success(null,'Produk dihapus');}
 private function admin():array{$a=AdminAuth::user();if(!$a)$this->error('Unauthorized',401);return $a;}
}
