<?php
namespace App\Controllers\Webhook;use App\Core\Controller;
class Biteship extends Controller {
 private function guard():void{$token=(string)(defined('Env::BITESHIP_WEBHOOK_TOKEN')?\Env::BITESHIP_WEBHOOK_TOKEN:'');if($token==='')return;$given=(string)($_SERVER['HTTP_X_BITESHIP_TOKEN']??$this->query('token',''));if(!hash_equals($token,$given))$this->error('Invalid webhook token',401);}
 private function delivery(string $bid):array{$d=$this->db()->query('SELECT id,order_id FROM vp_order_deliveries WHERE biteship_order_id=? LIMIT 1',[$bid])->row_array();if(!$d)$this->error('Delivery not found',404);return $d;}
 public function status():void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->guard();$b=$this->getBody();$bid=trim((string)($b['order_id']??''));$status=trim((string)($b['status']??''));if($bid===''||$status==='')$this->error('Unknown payload',422);$now=$GLOBALS['now']??date('Y-m-d H:i:s');$d=$this->delivery($bid);$delivered=$status==='delivered';$failed=in_array($status,['cancelled','rejected','returned','disposed'],true);$this->db()->update('vp_order_deliveries',['status'=>$status,'delivered_at'=>$delivered?$now:null,'updated_at'=>$now],['id'=>(int)$d['id']]);$orderStatus=$delivered?'completed':($failed?'cancelled':'shipped');$this->db()->update('vp_orders',['status'=>$orderStatus,'updated_at'=>$now],['id'=>(int)$d['order_id']]);$this->success(['order_id'=>$bid,'status'=>$status,'order_status'=>$orderStatus],'Status updated');}
 public function waybill():void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->guard();$b=$this->getBody();$bid=trim((string)($b['order_id']??''));$waybill=trim((string)($b['courier_waybill_id']??''));$status=trim((string)($b['status']??''));if($bid===''||$waybill==='')$this->error('Unknown payload',422);$now=$GLOBALS['now']??date('Y-m-d H:i:s');$d=$this->delivery($bid);$data=['tracking_number'=>$waybill,'updated_at'=>$now];if($status!=='')$data['status']=$status;$this->db()->update('vp_order_deliveries',$data,['id'=>(int)$d['id']]);$this->success(['order_id'=>$bid,'waybill'=>$waybill],'Waybill updated');}
 public function price():void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->guard();$b=$this->getBody();$bid=trim((string)($b['order_id']??''));if($bid==='')$this->error('Unknown payload',422);$price=(float)($b['price']??0);$now=$GLOBALS['now']??date('Y-m-d H:i:s');$d=$this->delivery($bid);$order=$this->db()->query('SELECT id,subtotal FROM vp_orders WHERE id=? LIMIT 1',[(int)$d['order_id']])->row_array();if(!$order)$this->error('Order not found',404);$total=(float)$order['subtotal']+$price;$this->db()->update('vp_orders',['shipping_cost'=>$price,'total'=>$total,'updated_at'=>$now],['id'=>(int)$order['id']]);$this->db()->update('vp_payments',['gross_amount'=>$total,'updated_at'=>$now],['order_id'=>(int)$order['id']]);$this->success(['order_id'=>$bid,'price'=>$price,'total'=>$total],'Price updated');}
}
