<?php
namespace App\Controllers\Webhook;use App\Core\Controller;
class Biteship extends Controller {
 private function guard():void{$token=(string)(defined('Env::BITESHIP_WEBHOOK_TOKEN')?\Env::BITESHIP_WEBHOOK_TOKEN:'');if($token==='')return;$given=(string)($_SERVER['HTTP_X_BITESHIP_TOKEN']??$this->query('token',''));if(!hash_equals($token,$given))$this->error('Invalid webhook token',401);}
 private function delivery(string $bid):array{$d=$this->db()->query('SELECT id,order_id FROM vp_order_deliveries WHERE biteship_order_id=? LIMIT 1',[$bid])->row_array();if(!$d)$this->error('Delivery not found',404);return $d;}
 private function applyStatus(array $d,string $status):void{$now=$GLOBALS['now']??date('Y-m-d H:i:s');$delivered=$status==='delivered';$failed=in_array($status,['cancelled','rejected','returned','disposed'],true);$this->db()->update('vp_order_deliveries',['status'=>$status,'delivered_at'=>$delivered?$now:null,'updated_at'=>$now],['id'=>(int)$d['id']]);$orderStatus=$delivered?'completed':($failed?'cancelled':'shipped');$this->db()->update('vp_orders',['status'=>$orderStatus,'updated_at'=>$now],['id'=>(int)$d['order_id']]);}
 private function applyWaybill(array $d,string $waybill):void{$now=$GLOBALS['now']??date('Y-m-d H:i:s');$this->db()->update('vp_order_deliveries',['tracking_number'=>$waybill,'updated_at'=>$now],['id'=>(int)$d['id']]);}
 private function applyPrice(array $d,float $price):void{$now=$GLOBALS['now']??date('Y-m-d H:i:s');$order=$this->db()->query('SELECT id,subtotal FROM vp_orders WHERE id=? LIMIT 1',[(int)$d['order_id']])->row_array();if(!$order)return;$total=(float)$order['subtotal']+$price;$this->db()->update('vp_orders',['shipping_cost'=>$price,'total'=>$total,'updated_at'=>$now],['id'=>(int)$order['id']]);$this->db()->update('vp_payments',['gross_amount'=>$total,'updated_at'=>$now],['order_id'=>(int)$order['id']]);}
 public function index():void{$this->handleCors();$b=$this->getBody();$bid=trim((string)($b['order_id']??''));if($bid===''){http_response_code(200);header('Content-Type: text/plain; charset=utf-8');echo 'ok';return;}if(!$this->isPost())$this->error('Method not allowed',405);$this->guard();$d=$this->delivery($bid);$applied=[];if(!empty($b['courier_waybill_id'])){$this->applyWaybill($d,(string)$b['courier_waybill_id']);$applied[]='waybill';}if(isset($b['price'])&&(float)$b['price']>0){$this->applyPrice($d,(float)$b['price']);$applied[]='price';}if(!empty($b['status'])){$this->applyStatus($d,(string)$b['status']);$applied[]='status';}$this->success(['order_id'=>$bid,'applied'=>$applied],'Webhook processed');}
 public function status():void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->guard();$b=$this->getBody();$bid=trim((string)($b['order_id']??''));$status=trim((string)($b['status']??''));if($bid===''||$status==='')$this->error('Unknown payload',422);$d=$this->delivery($bid);$this->applyStatus($d,$status);$this->success(['order_id'=>$bid,'status'=>$status],'Status updated');}
 public function waybill():void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->guard();$b=$this->getBody();$bid=trim((string)($b['order_id']??''));$waybill=trim((string)($b['courier_waybill_id']??''));$status=trim((string)($b['status']??''));if($bid===''||$waybill==='')$this->error('Unknown payload',422);$d=$this->delivery($bid);$this->applyWaybill($d,$waybill);if($status!=='')$this->applyStatus($d,$status);$this->success(['order_id'=>$bid,'waybill'=>$waybill],'Waybill updated');}
 public function price():void{$this->handleCors();if(!$this->isPost())$this->error('Method not allowed',405);$this->guard();$b=$this->getBody();$bid=trim((string)($b['order_id']??''));if($bid==='')$this->error('Unknown payload',422);$d=$this->delivery($bid);$this->applyPrice($d,(float)($b['price']??0));$this->success(['order_id'=>$bid,'price'=>(float)($b['price']??0)],'Price updated');}
}
